baseURL = 'http://hugo-quickstart-template.netlify.com'
languageCode = 'en-us'
title = 'Netlify + Hugo Quickstart'
theme = 'hugo-theme-learn'

[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "green"
